### ISSUE TITLE
Can't request autocraft of Quantum Infusion at terminal

### ISSUE THREAD

**Issue by Horosam** [pedroksl/AdvancedAE#34] opened 2024-11-05 20:53 UTC
**Mod loader**
NeoForge

**Minecraft version**
1.21.1

**Mod version**
1.1.0

**Modloader version**
Neoforge: 21.1.73

**Issue description**
Using 5B of water and 1 Quantum Infused dust at a reaction chamber produces 1B of Quantum Infusion, but inserting a encoded pattern with the same recipe into any type of pattern provider and trying requesting the crafting results into a non interactive recipe into the terminal.
![2024-11-04_20 31 18](https://github.com/user-attachments/assets/b51c222c-c89e-46a7-89da-a99408afe95c)

**Comment by pedroksl** [comment] 2024-11-05 22:30
I have a few questions:

* I can see you are using JEI. JEI has an issue where it doesn't encode the fluids in the recipe. Did you add that manually?
* Second question, you said "any pattern provider" and that makes me wonder: Was pattern provider was touching the reaction chamber?
* What was the configuration of that Pattern Provider? Did you use any redstone logic or blocking mode or wait until returned?
* Did you manually export the fluid to keep them in stock? (I've seen people export water into it to keep it full)
* Did you configure the chamber to export correctly into the pattern provider? It can export to adjacent machines if not set properly
* Can you provide screenshots of the things mentioned in these questions? (Pattern, Pattern Provider, Reaction Chamber, Chamber export configuration)

**Comment by Horosam** [comment] 2024-11-05 22:49
I've added the recipe manually.
and I tried using both the block and flat versions of pattern providers.
![2024-11-05_19 37 18](https://github.com/user-attachments/assets/e0f22591-d967-40c2-92a5-eebbbd4a7e08)
![2024-11-05_19 38 08](https://github.com/user-attachments/assets/3f49b0ef-f621-40f3-a558-f49bcc955c2a)
![2024-11-05_19 38 41](https://github.com/user-attachments/assets/9d5c9f21-f66c-4c38-ad2b-b722b7da04ed)
![2024-11-05_19 38 53](https://github.com/user-attachments/assets/02f56703-ea90-4493-afb2-aef62c4feee7)
![2024-11-05_19 35 47](https://github.com/user-attachments/assets/52770461-b1d6-4b47-a7b4-3d3306b8ab59)
![2024-11-05_19 36 05](https://github.com/user-attachments/assets/15eb5731-bd91-4378-9cbe-5390a2255712)

**Comment by pedroksl** [comment] 2024-11-05 23:21
I'm still missing this part
> What was the configuration of that Pattern Provider? Did you use any redstone logic or blocking mode or wait until returned?
and a screenshot of the provider UI.

Also, can you please click both "x" buttons on the chamber interface, as a test?

**Comment by Horosam** [comment] 2024-11-06 00:04
the configuration:
![2024-11-05_20 53 31](https://github.com/user-attachments/assets/c76140dd-aab4-4380-98c8-0d47cc9b027e)
![2024-11-05_20 53 33](https://github.com/user-attachments/assets/5e6be06e-4e6d-4b53-957d-9eedbd3a32b5)
![2024-11-05_20 53 35](https://github.com/user-attachments/assets/ffff5a9c-4396-40c3-8a1b-c0fae885d7fd)
I also tried downloading EMI yesterday and using the recipe provided for the reaction chamber but that also didnt work.

**Comment by pedroksl** [comment] 2024-11-06 00:34
Very weird bug, and unfortunately I'm not able to reproduce it in any way.
The last thing I could ask you to try is to break the block and place it again. (Remember to configure output before requesting another auto craft)

**Comment by Horosam** [comment] 2024-11-06 01:44
Done and while at it ,I reinstaled the pack . All without susccess.

**Comment by pedroksl** [comment] 2024-11-06 01:52
That is a bit extreme, but thanks.
I do have another question. Do you have fluid cells in your network? Any place where the output fluid could go?

**Comment by pedroksl** [comment] 2024-11-06 01:53
Also, does it at least create a request?
![image](https://github.com/user-attachments/assets/c4d2e65d-3c74-4018-b7da-1e743471c219)

**Comment by Horosam** [comment] 2024-11-06 01:59
No, I cant interact with the Quantum Infusion recipe at the terminal.

**Comment by pedroksl** [comment] 2024-11-06 02:24
I've never seen that happen before. Can you send me some logs?
Go in game and try to request with normal click and middle mouse click. Then send me the "latest.log" so that I can check if any errors are happening related to my mod specifically. If this is happening on a server, please send the lastest.log of the server, too.

**Comment by Horosam** [comment] 2024-11-06 02:41
OK, out of all things, I didnt try middle mouse click. That worked , I was able to order using middle mouse. 
Many thanks.

**Comment by pedroksl** [comment] 2024-11-06 02:44
Thankfully this wasn't a bug because it couldn't been nasty and ae2 related. Closing this issue now.

**Closed by pedroksl** 2024-11-06 02:44 UTC
