### ISSUE TITLE
Weird crash after breaking part of Quantum CPU

### ISSUE THREAD

**Issue by GordonHollow** [pedroksl/AdvancedAE#8] opened 2024-09-11 16:40 UTC
Just notice one of my autocraft request not complete for long, checked what CPU it's in, and it was quantum CPU
can't close task, button inactive, see part of QuantumCPU in one chunk is offline texture, part in other chunk is offline textures, break one block expecting rebuild will fix block - game crashed with this log

[crash-2024-09-11_21.02.53-server.txt](https://github.com/user-attachments/files/16966780/crash-2024-09-11_21.02.53-server.txt)

**Comment by MorganNya** [comment] 2024-09-12 03:16
+1 to this. Pretty much the same crash log und same issue. Couldnt cancel it und when breaking one Block of the Quantum Computer Multiblock, the Server crashed with the above crash log. After manual Server restart  you could just complete the structur again with no problems.

**Comment by pedroksl** [comment] 2024-09-12 12:33
This should be fixable reasonably easy but I have to ask something. Both of you are playing in servers? It seems I can't reproduce most of the issues and I'm starting to wonder if it's all because I am only testing in singleplayer worlds.

**Comment by GordonHollow** [comment] 2024-09-12 13:12
I'm playing singleplayer

**Comment by MorganNya** [comment] 2024-09-12 14:49
I'm playing on a multiplayer Server, Modpack ATM10 version 0.48

**Comment by pedroksl** [comment] 2024-09-14 07:17
Although not entirely sure about it, there were two potencial ways of the quantum computer crashing the instance that were fixed in the last release. Along that, the logic for how the quantum computer handles jobs and internally created cpu's has changed, and this could impact the original issue of sometimes losing control over the quantum computer. For now all of this is theorical, as I haven't been able to reproduce the issues you experienced but I would like to ask if you could try out the new release and try to reproduce the same issues again. Hopefully these will also be fixed.

I would like to kindly request that you report back if the problems are still there or if they are fixed so that I can change the status of the issue.

**Comment by MorganNya** [comment] 2024-09-14 08:06
We are a bit limited by the Update Intervall of Nitrado for the Modpack but I will try it when I get the chance too, but could be two-three weeks sadly

**Comment by MorganNya** [comment] 2024-09-23 20:13
We are now on ATM 10 Version 0.53 and I didn't encounter the crash again.

**Comment by pedroksl** [comment] 2024-09-23 22:31
Thank you for the report. Although the creator of the issue did not report back, I think it's safe to close this issue ofr now. Feel free to reopen it or create a new one in case the issue reappears.

**Closed by pedroksl** 2024-09-23 22:31 UTC
Labels: bug
