### ISSUE TITLE
quantum crafter wont accept energy

### ISSUE THREAD

**Issue by balla2185** [pedroksl/AdvancedAE#40] opened 2024-11-12 15:58 UTC
on ATM 10 build.18 we have quantum crafter connected to every different type of cable to controller its at 0/8k energy and will not run

**Comment by pedroksl** [comment] 2024-11-12 16:22
AE2 machines don't fill their energy buffer when connected to a network to avoid wasted energy. But it also doesn't need to be filled to work. All it needs is access to storage and an energy buffer somewhere in the system.

I'm using one to craft insanium essence right now, in the same ATM version that is just a storage bus connected to it and a Crystal Resonance Generator (provides 20FE/t) and that is enough for it to work.

I would need more information about your system to debug why yours isn't working.

**Comment by pedroksl** [comment] 2024-11-12 16:27
- Does it have acess to storage?
- Is There a power source somewhere (and the network is not flickering for some other reason)?
- Does it have space to export the items?
- Have you tried exporting to its own inventory to see if that works?
- Did you set the patterns correctly?
- Does it have access to all required ingredients to craft the patterns?
- Did you enable the patterns clicking the button below the patterns?
- Did you set any stock/limit configuration? If so, what did you set it to?

Attached screenshots would help greatly, specially regarding the position in world, connections to the system, cable, power, etc.

**Comment by balla2185** [comment] 2024-11-13 15:40
here are some pictures connected to controller and we are using ae to give power and we have a cell attached tot he controller
![Crafter ](https://github.com/user-attachments/assets/963c3c14-4d75-4821-aef0-03445cb8b0bf)
![setup](https://github.com/user-attachments/assets/8ecadd0b-357e-4e75-843e-70d22734e6a0)
![pattern config](https://github.com/user-attachments/assets/3dc12762-ed94-40d9-b766-ccd1ad8051a7)

**Comment by pedroksl** [comment] 2024-11-13 16:35
Do you have the prerequisite items in the system?

The quantum crafter does *not* craft pre requisites.
If you want this to work you need to have the alloy and control circuit available in the system, either through a requester or another quantum crafter (for crafting patterns).

If I were to request crafts for previous items it would be insanely complicated (to avoid over requesting) and insanely laggy (too much stuff happens every tick already).

I believe this is the root cause of your issue. Just set the alloy in the me requester and create additional patterns for the control circuits, then add the basic control circuit to another requester.

**Comment by balla2185** [comment] 2024-11-13 17:58
Ill test why the option to set levels inside if it can't create them?

**Comment by pedroksl** [comment] 2024-11-13 21:45
The purpose of those settings is to avoid overconsumption. An example of this is Mystical Aggriculture Essences. If you have no "keep x amount" it would disappear from storage as soon as you downcraft it from the next tier. Or anything else you actually want to keep some in storage and not consume it all.

The Quantum Crafter works in the same way any other auto crafter would, except you don't need to feed it the materials. If you want to request the entire crafting process, what you need is actually the requester. The quantum crafter is better used for stuff you need to run indefinitely or super fast.

**Comment by balla2185** [comment] 2024-11-14 13:45
Awesome thank you it is working just super fast. Just wish it always kept
that animated graphic that looks sick

**Comment by pedroksl** [comment] 2024-11-14 23:54
The animation is supposed to be an indicator that the machine is running, so unfortunately it will probably stay that way unless I find a better way to convey that while keeping the animation. But thanks for the suggestion, I might see if I can make that work in the future.

Closing this issue right now as it wasn’t an actual bug, rather a misunderstanding.

**Closed by pedroksl** 2024-11-14 23:54 UTC
