### ISSUE TITLE
Equipping Quantum Armor with Wireless Charging upgrades generates 2.1 GFE/s for the network with AppliedFlux cells while holding Digital Miner (Mekanism)

### ISSUE THREAD

**Issue by Kribylet** [pedroksl/AdvancedAE#66] opened 2024-12-10 00:52 UTC
⁸I'm really not sure why.

DW20 1.4.1 pack, my energy source is an Extreme Reactor generating 18~ KFE/t (5x5x5 core, Redfrigium, passive) set up to feed an energy acceptor and flux acceptor immediately at the charge port through 1 Ultimate Universal Cable (Mekanism).

When Wireless mode is enabled on the quantum armor, my energy generation spikes by 2.1 trillion FE/s.

At the time I was holding 2 Ultimate Energy Cube, 1 fully upgraded Mining Gadget, 1 atomic disassembler and 1 Armored Free Runners. Nothing else is inventory chargable AFAIK. 

.. Some testing showed that holding a Digital Miner (Mekanism) in isolation while wearing the Quantum Armor caused the energy generation spike to occur. Holding anything except the Digital Miner the energy spike did not occur. I had previously had it deployed with a Quantum Entangloporter (Mekanism) linking it for power in the mining dimension, not sure if there is some related state there or not.

**Comment by pedroksl** [comment] 2024-12-13 02:38
I tried to reproduce this bug but, unfortunately, I was unable to.

![image](https://github.com/user-attachments/assets/0de6c188-fb80-4a8c-a3e4-bfdcfc780dbb)

Did you check if power was actually going into the system? Did you measure it using my monitors? Did you wait for the values to settle? The monitor does take some time with wrong readings if you use the configurator to change the measure rate. Outside of these things, I would need to find a way to reproduce the issue to be able to potentially fix it. However, my code doesn't create power out of nothing, so I don't know what kind of integration issue could be causing this.

**Comment by Kribylet** [comment] 2024-12-14 15:38
![energy_ae_setup](https://github.com/user-attachments/assets/574936c7-e9c0-4186-9064-6ef04c55dcac)
![digital_miner_setup_before_teardown](https://github.com/user-attachments/assets/cccb70fd-32e3-48ba-bc89-b457f533f868)
![energy_ae_setup_holding_digital_miner](https://github.com/user-attachments/assets/03789b41-1bd5-4673-8742-79e42482008b)
![energy_cells_filling](https://github.com/user-attachments/assets/415422ae-e054-4b59-ac2a-eaa98c8f2f3d)

Here is the setup I created in singleplayer to repro this issue

1. Set up reactor in overworld
2. AE network: ME Controller, Energy Cell, ME Drive + 9 256M FE Storage Cells
3. AE-Reactor link: Ultimate Universal Energy Cable, Flux Accessor, Energy Acceptor to AE net
4. Quantum Entangloporter linked with Flux Accessor, set to private net
5. Go to mining dimension
6. Set up digital miner with 32 energy upgrades, 16 speed upgrades
7. Set up entangloporter and link power by ultimate universal cable
8. Wait for digital miner to fully charge
9. Wear full unlinked Quantum Armor set
10. Equip wireless upgrade on each part
11. Set up wireless access point on AE network, link each armor piece
12. Wait for armor to fully charge (I sped this up with a SolarGeneration Ultimate Solar Panel in this case)
13. As armor fully charges, the energy spike occurs.

**Comment by pedroksl** [comment] 2024-12-15 21:47
I think I might have found what is causing the issue on the code side. I'm still unsure how you ended up in that situation in the first place, as nothing in here seems like it could trigger such an error. But apparently I had some mistakes when converting AE <-> FE, which might have lead to extracting x from the grid, failing to insert more into inventory items and returning 2x instead of x. Leading to a net positive of max int. I'm pushing a small change to this logic that hopefully solves this. However, I'm still unsure why it happened in the first place, since before getting to that point I check if the item still accepts energy and it shouldn't in this case. Anyway, hopefully my next release will fix this, when it happens.

**Comment by pedroksl** [comment] 2024-12-15 21:59
I just release a new version containing the change I talked about earlier. Hopefully that fixes this issue.

**Comment by Kribylet** [comment] 2024-12-16 12:55
Due to AE base mod version restrictions I was unable to retry my world using 1.4.1 for better isolation, however the issue appears to still be present using DW20 1.8.0 after manually updating AdvancedAE to the new release:

![image](https://github.com/user-attachments/assets/2dd41786-5610-42aa-8e62-d7f4e57aec3c)

Power spike stops when dropping the digital miner as before, visible on the monitors after they update and the storage cells byte usage increasing when viewed in the ME drive.

Tangentially, we've found another issue related to the digital miner on our MP server where it is valid as a recharging object in the ChargingGadgets mod charging station. Attempting to recharge it in the charging station of that mod causes a server-wide freeze that requires a manual restart. Not sure if that's relevant, but maybe the Digital Miner itself is incorrectly tagged somehow?

**Comment by pedroksl** [comment] 2024-12-16 16:15
If that's the case, this could be caused by a faulty implementation of the EnergyStorage Capability of the digital miner. Would you mind opening an issue in Mekanism's github and asking them to evaluate if that's the case?

**Comment by pedroksl** [comment] 2024-12-19 05:46
Hey, Just wanted to let you know that I found out the issue, and how to reproduce it. I've posted an issue in the Mekanism Unleashed addon mod, because it's what triggered it happening in the first place. But I've also added a safety measure in my code to preventing it happening in the future.

Thanks for the report, this will be in the next release.

**Closed by pedroksl** 2024-12-19 05:46 UTC

**Comment by Kribylet** [comment] 2024-12-19 07:11
Awesome! Just wanna close here by saying I enjoy your mod a lot and to thank you for making it!
